import state
import usb1
import usb

"""
Base class for all exceptions which may be generated by the test.
"""
class CynthionTestError(Exception):
    def __init__(self, msg):
        self.msg = msg
        self.step = ".".join(str(s) for s in state.step)

# Define subclasses with associated three-letter codes.
for code, name in (
    ('EXC', 'UnexpectedError'),
    ('INT', 'TestStoppedError'),
    ('USR', 'FailButtonError'),
    ('DEP', 'DependencyError'),
    ('GF1', 'GF1Error'),
    ('BMP', 'BMPError'),
    ('TYC', 'TychoError'),
    ('PSU', 'PowerSupplyError'),
    ('CAL', 'CalibrationError'),
    ('LOW', 'ValueLowError'),
    ('HIG', 'ValueHighError'),
    ('WRG', 'ValueWrongError'),
    ('CMD', 'CommandError'),
    ('SLF', 'SelfTestError'),
    ('REG', 'RegisterError'),
    ('BTN', 'ButtonError'),
    ('CBL', 'CableError'),
    ('USB', 'USBCommsError'),
):
    globals()[name] = type(name, (CynthionTestError,), {'code': code})

"""
Takes an exception and if it is not a CynthionTestError, raises a
suitable CynthionTestError wrapper.
"""
def wrap_exception(exc, usb_err_type=None):
    usb_exceptions = (usb.USBError, usb1.USBError)
    if isinstance(exc, CynthionTestError):
        return
    elif isinstance(exc, KeyboardInterrupt):
        raise TestStoppedError("Test stopped by keyboard interrupt.")
    elif usb_err_type is not None and isinstance(exc, usb_exceptions):
        raise usb_err_type("USB error: " + str(exc))
    else:
        raise UnexpectedError(str(exc))

"""
Context manager which converts non-CynthionTestError exceptions.
"""
class error_conversion():
    def __init__(self, usb_err_type=None):
        self.usb_err_type = usb_err_type
    def __enter__(self):
        pass
    def __exit__(self, exc_type, exc_value, exc_tb):
        if exc_value is not None:
            wrap_exception(exc_value, self.usb_err_type)
        return False
